src/routes/web.php
<?php

// Auth Configuration
if (config('miamilaw.auth') === 'azure') {
    Route::get('/login', function () {
        return redirect('/login/microsoft');
    })->name('login');

    Route::match(['GET', 'POST'], '/logout', function () {
        Auth::logout();
        Session::flush();

        return redirect('/');
    })->name('logout');
} elseif (config('miamilaw.auth') === 'local') {
    Route::get('/login/microsoft', function () {
        return redirect('/login');
    });

    Route::get('/login/microsoft/callback', function () {
        return redirect('/login');
    });

    Route::group(['middleware' => ['web'], 'namespace'=>'App\Http\Controllers'], function () {
        Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

        Route::get('/logout', function () {
            Auth::logout();
            Session::flush();

            return redirect('/');
        });
    });
}

// MiamiLaw Controllers
Route::group(['namespace' => '\MiamiLaw\Base\Http\Controllers'], function () {

    // User Controller
    Route::resource('admin/user', 'UserController');
    Route::get('/user/profile', 'UserController@profile')
        ->name('user.profile');

    // Menu Admin
    Route::resource('admin/menu', 'MenuController')->except(['show']);
    Route::get('admin/menu/{menu}/items', 'MenuController@itemsIndex')
         ->name('menu.items.index');
    Route::get('admin/menu/{menu}/items/create', 'MenuController@itemsCreate')
         ->name('menu.items.create');
    Route::post('admin/menu/{menu}/items', 'MenuController@itemsStore')
         ->name('menu.items.store');
    Route::get('admin/menu/{menu}/items/{item}/edit', 'MenuController@itemsEdit')
         ->name('menu.items.edit');
    Route::delete('admin/menu/{menu}/items/{item}', 'MenuController@itemsDestroy')
         ->name('menu.items.destroy');
    Route::match(['put', 'patch'], 'admin/menu/{menu}/items/{item}', 'MenuController@itemsUpdate')
         ->name('menu.items.update');
});

src/Models/Menu.php
<?php

namespace MiamiLaw\Base\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    //

    protected $fillable = [
        'name',
        'description',
        'permanent',
    ];

    public function items()
    {
        return $this->hasMany(MenuItem::class)->orderBy('weight', 'asc');
    }
}

src/Http/Controllers/MenuController.php
<?php
/**
 * Created by PhpStorm.
 * User: mgavidia
 * Date: 5/24/19
 * Time: 11:52 AM.
 */

namespace MiamiLaw\Base\Http\Controllers;

use Illuminate\Http\Request;
use MiamiLaw\Base\Models\Menu;
use MiamiLaw\Base\Models\MenuItem;

class MenuController extends Controller
{
    /**
     * MenuController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkadmin');
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::all();

        return view('miamilaw::admin.menu.index', compact('menus'));
    }

    public function create()
    {
        $title = 'Create new Menu';

        return view('miamilaw::admin.menu.create', compact('title'))
            ->withErrors([]);
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'description' => 'required',
        ]);

        Menu::create($request->all());

        return redirect()->route('menu.index')
            ->with('success', 'Menu successfully created.');
    }

    public function edit($id)
    {
        $menu = Menu::where('id', $id)->first();

        if (! $menu || $menu->permanent === '1') {
            abort(401, 'Invalid request.');
        }

        $title = 'Edit Menu';

        return view('miamilaw::admin.menu.edit', compact('menu', 'title'))
            ->withErrors([]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
        ]);

        $menu = Menu::where('id', $id)->first();

        if (! $menu) {
            abort(401, 'Invalid request.');
        }

        $menu->update($request->all());

        return redirect()->route('menu.index')
                         ->with('success', 'Menu successfully updated.');
    }

    public function destroy($id)
    {
        $menu = Menu::where('id', $id)->first();

        if (! $menu) {
            abort(401, 'Invalid request.');
        }

        $items_deleted = $menu->items()->delete();

        $name = $menu->name;

        $menu->delete();

        return redirect()->route('menu.index')
                         ->with('success', "Successfully deleted $name menu and $items_deleted items.");
    }

    public function itemsIndex($menu_id)
    {
        $menu = Menu::where('id', $menu_id)->first();

        if (! $menu) {
            abort(401, 'Invalid request.');
        }

        return view('miamilaw::admin.menu.item.index', compact('menu'));
    }

    public function itemsCreate($menu_id)
    {
        $menu = Menu::where('id', $menu_id)->first();

        if (! $menu) {
            abort(401, 'Invalid request.');
        }

        return view('miamilaw::admin.menu.item.create', compact('menu'))
            ->withErrors([]);
    }

    public function itemsStore(Request $request)
    {
        $validatedData = $request->validate([
            'menu_id' => 'required',
            'name' => 'required',
            'route' => 'required',
            'weight' => 'required',
        ]);

        /*$item = MenuItem::create($request->all());*/

        $menu = Menu::where('id', $request->get('menu_id'))->first();

        $menu->items()->save(new MenuItem($request->all()));

        return redirect()->route('menu.items.index', $request->get('menu_id'))
                         ->with('success', 'Menu Item successfully created.');
    }

    public function itemsEdit($menu_id, $id)
    {
        $item = MenuItem::where('id', $id)->first();

        if (! $item) {
            abort(401, 'Invalid request.');
        }

        return view('miamilaw::admin.menu.item.edit', compact('menu_id', 'item'))
            ->withErrors([]);
    }

    public function itemsUpdate(Request $request, $menu_id, $id)
    {
        $request->validate([
            'menu_id' => 'required',
            'name' => 'required',
            'route' => 'required',
            'weight' => 'required',
        ]);

        $item = MenuItem::where('id', $id)->first();

        if (! $item) {
            abort(401, 'Invalid request.');
        }

        $item->update($request->all());

        return redirect()->route('menu.items.index', $item->menu_id)
                         ->with('success', 'Menu item successfully updated.');
    }

    public function itemsDestroy($menu_id, $id)
    {
        $menu = Menu::where('id', $menu_id)->first();

        $menu->items()->where('id', $id)->delete();

        return redirect()->route('menu.items.index', $menu_id)
                         ->with('success', 'Menu item successfully deleted.');
    }
}

src/resources/views/admin/menu/create.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    {{ $title }}
@endsection

@section('content')
    @component('miamilaw::components.form.form', [
                'action' => [
                    'route' => 'menu.store',
                    'parameters' => []
                ],
                'cancel' => [
                    'route' => 'menu.index',
                    'parameters' => []
                ],
                ])
            @component('miamilaw::components.form.input', [
                        'name' => 'name',
                        'icon' => 'user',
                        'placeholder' => 'Name',
                        'required' => true,
                        'autofocus' => true,
                        'errors' => $errors,
                        ])
            @endcomponent
            @component('miamilaw::components.form.input', [
                        'name' => 'description',
                        'icon' => 'info',
                        'placeholder' => 'Description',
                        'required' => true,
                        'errors' => $errors,
                        ])
            @endcomponent
            @component('miamilaw::components.form.checkbox', [
                        'name' => 'permanent',
                        'description' => 'Is permanent?',
                        'disabled' => true,
                        'errors' => $errors,
                        ])
            @endcomponent
    @endcomponent
@endsection

src/resources/views/admin/menu/edit.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    {{ $title }}
@endsection

@section('content')
    @component('miamilaw::components.form.form', [
                'action' => [
                    'route' => 'menu.update',
                    'parameters' => [
                        'id' => $menu->id
                    ]
                ],
                'cancel' => [
                    'route' => 'menu.index',
                    'parameters' => []
                ],
                'method' => 'PUT'
                ])
        @component('miamilaw::components.form.input', [
                    'name' => 'name',
                    'icon' => 'user',
                    'placeholder' => 'Name',
                    'required' => true,
                    'autofocus' => true,
                    'value' => $menu->name,
                    'errors' => $errors,
                    ])
        @endcomponent
        @component('miamilaw::components.form.input', [
                    'name' => 'description',
                    'icon' => 'info',
                    'placeholder' => 'Description',
                    'required' => true,
                    'value' => $menu->description,
                    'errors' => $errors,
                    ])
        @endcomponent
        @component('miamilaw::components.form.checkbox', [
                    'name' => 'permanent',
                    'description' => 'Is permanent?',
                    'checked' => $menu->permanent,
                    'disabled' => true,
                    'errors' => $errors,
                    ])
        @endcomponent
    @endcomponent
@endsection

src/resources/views/admin/menu/index.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    Menu Configuration
@endsection

@section('content')
    @if (session()->get('success'))
        <div class="ui positive message">
            <div class="header">{{ session()->get('success') }}</div>
        </div>
    @endif
    <a href="{{ route('menu.create') }}" class="positive ui fluid large button">
        <i class="icon plus square outline"></i>
        Create new
    </a>
    <table class="ui celled striped table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Permanent</th>
                <th>Total Links</th>
                <th>Functions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($menus as $menu)
                <tr>
                    <td data-label="Name">{{ $menu->name }}</td>
                    <td data-label="Descriptione">{{ $menu->description }}</td>
                    <td data-label="Permanent">{{ $menu->permanent === '1' ? 'Yes' : 'No'}}</td>
                    <td data-label="Total Links">{{ $menu->items()->count() }}</td>
                    <td data-label="Functions">
                        @if ($menu->permanent === '1')
                            <div class="ui left floated buttons">
                                <div class="ui green disabled button">Edit</div>
                                <a href="{{ route('menu.items.index', $menu->id) }}" class="ui blue button">Edit Links</a>
                            </div>
                            <div class="ui right floated red disabled button">Delete</div>
                        @else
                            <form action="{{ route('menu.destroy', $menu)}}" method="post" onsubmit="return confirm('Are you sure you want to Delete the Menu?');">
                                @csrf
                                @method('DELETE')
                                <div class="ui left floated buttons">
                                    <a href="{{ route('menu.edit',$menu->id) }}" class="ui green button">Edit</a>
                                    <a href="{{ route('menu.items.index', $menu->id) }}" class="ui blue button">Edit Links</a>
                                </div>
                                <button class="ui right floated red button" type="submit">Delete</button>
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection