src/routes/web.php
<?php

// Auth Configuration
if (config('miamilaw.auth') === 'azure') {
    Route::get('/login', function () {
        return redirect('/login/microsoft');
    })->name('login');

    Route::match(['GET', 'POST'], '/logout', function () {
        Auth::logout();
        Session::flush();

        return redirect('/');
    })->name('logout');
} elseif (config('miamilaw.auth') === 'local') {
    Route::get('/login/microsoft', function () {
        return redirect('/login');
    });

    Route::get('/login/microsoft/callback', function () {
        return redirect('/login');
    });

    Route::group(['middleware' => ['web'], 'namespace'=>'App\Http\Controllers'], function () {
        Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

        Route::get('/logout', function () {
            Auth::logout();
            Session::flush();

            return redirect('/');
        });
    });
}

// MiamiLaw Controllers
Route::group(['namespace' => '\MiamiLaw\Base\Http\Controllers'], function () {

    // User Controller
    Route::resource('admin/user', 'UserController');
    Route::get('/user/profile', 'UserController@profile')
        ->name('user.profile');

    // Menu Admin
    Route::resource('admin/menu', 'MenuController')->except(['show']);
    Route::get('admin/menu/{menu}/items', 'MenuController@itemsIndex')
         ->name('menu.items.index');
    Route::get('admin/menu/{menu}/items/create', 'MenuController@itemsCreate')
         ->name('menu.items.create');
    Route::post('admin/menu/{menu}/items', 'MenuController@itemsStore')
         ->name('menu.items.store');
    Route::get('admin/menu/{menu}/items/{item}/edit', 'MenuController@itemsEdit')
         ->name('menu.items.edit');
    Route::delete('admin/menu/{menu}/items/{item}', 'MenuController@itemsDestroy')
         ->name('menu.items.destroy');
    Route::match(['put', 'patch'], 'admin/menu/{menu}/items/{item}', 'MenuController@itemsUpdate')
         ->name('menu.items.update');
});

src/Http/Controllers/UserController.php
<?php

namespace MiamiLaw\Base\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use MiamiLaw\Base\Models\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::check() && ! Auth::user()->hasRole('admin')) {
            return redirect()->route('user.show', Auth::user()->id);
        }

        $users = User::all();

        return view('miamilaw::admin.user.index', compact('users'));
    }

    public function create()
    {
        Auth::user()->authorizeRoles(['admin']);
        $roles = Role::all();

        return view('miamilaw::admin.user.create', compact('roles'))
            ->withErrors([]);
    }

    public function store(Request $request)
    {
        Auth::user()->authorizeRoles(['admin']);
        $validatedData = $request->validate([
            'name',
            'email',
        ]);

        $defaults = [
            'name' => $request->get('name'),
            'email' => $request->get('email'),
        ];

        if ($request->get('azure_id') !== null) {
            $defaults['azure_id'] = $request->get('azure_id');
        }

        if ($request->get('password') !== null) {
            $defaults['password'] = HASH::make($request->get('password'));
        }

        $user = User::create($defaults);

        $user->roles()->attach($request->get('roles'));

        return redirect()->route('user.index')
            ->with('success', "User {$user->sname} was successfully created.");
    }

    public function edit($id)
    {
        if (Auth::user()->id !== intval($id) && ! Auth::user()->hasRole('admin')) {
            abort(401, 'This action is unauthorized.');
        }

        $user = User::where('id', $id)->first();

        $roles = Role::all();

        if (! $user) {
            abort(401, 'Invalid request.');
        }

        return view('miamilaw::admin.user.edit', compact('user', 'roles'))
            ->withErrors([]);
    }

    public function show($id)
    {
        if (Auth::user()->id !== intval($id) && ! Auth::user()->hasRole('admin')) {
            abort(401, 'This action is unauthorized.');
        }

        $user = User::where('id', $id)->first();
        $roles = Role::all();

        if (! $user) {
            abort(401, 'Invalid request.');
        }

        if (Auth::user()->hasRole('admin') || Auth::user()->id === $user->id) {
            return view('miamilaw::admin.user.show', compact('user', 'roles'))
                ->withErrors([]);
        }
        abort(401, 'Invalid request.');
    }

    public function profile()
    {
        return $this->show(Auth::user()->id);
    }

    public function update(Request $request, $id)
    {
        if (Auth::user()->id !== intval($id) && ! Auth::user()->hasRole('admin')) {
            abort(401, 'This action is unauthorized.');
        }

        $user = User::where('id', $id)->first();

        if (! $user) {
            abort(401, 'Invalid request.');
        }

        $validatedData = $request->validate([
            'name',
            'email',
        ]);

        $defaults = [
            'name' => $request->get('name'),
            'email' => $request->get('email'),
        ];

        if ($request->get('azure_id') !== null) {
            $defaults['azure_id'] = $request->get('azure_id');
        }

        if ($request->get('password') !== null) {
            $defaults['password'] = HASH::make($request->get('password'));
        }

        $user->update($defaults);

        if (Auth::user()->hasRole('admin')) {
            $user->roles()->sync($request->get('roles'));
        }

        return redirect()->route('user.index')
            ->with('success', "User {$user->name} successfully updated.");
    }

    public function destroy($id)
    {
        Auth::user()->authorizeRoles('admin');

        $user = User::where('id', $id)->first();

        if (! $user) {
            abort(401, 'Invalid request.');
        }

        if (Auth::user()->id === intval($id)) {
            return redirect()->route('user.index')
                ->with('warn', 'Cannot delete self.');
        } elseif (User::all()->count() === 1) {
            return redirect()->route('user.index')
                ->with('warn', 'Cannot delete only user.');
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('user.index')
            ->with('success', 'Successfully deleted User.');
    }
}

src/resources/views/admin/user/create.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    Create new User
@endsection

@section('content')
    @component('miamilaw::components.form.form', [
                'action' => [
                    'route' => 'user.store',
                    'parameters' => [
                    ]
                ],
                'cancel' => [
                    'route' => 'user.index',
                    'parameters' => []
                ],
                ])
        @component('miamilaw::components.form.input', [
                    'name' => 'name',
                    'icon' => 'user',
                    'placeholder' => 'Full Name',
                    'required' => true,
                    'autofocus' => true,
                    'errors' => $errors,
                    ])
        @endcomponent
        @component('miamilaw::components.form.input', [
                    'name' => 'email',
                    'icon' => 'mail',
                    'placeholder' => 'Email',
                    'required' => true,
                    'errors' => $errors,
                    ])
        @endcomponent
        @authtype('local')
            @component('miamilaw::components.form.input', [
                        'name' => 'password',
                        'type' => 'password',
                        'icon' => 'key',
                        'placeholder' => 'Set Password',
                        'errors' => $errors,
                        ])
            @endcomponent
        @elseauthtype('azure')
            @component('miamilaw::components.form.input', [
                        'name' => 'azure_id',
                        'icon' => 'cloud',
                        'placeholder' => 'Azure ID',
                        'errors' => $errors,
                        ])
            @endcomponent
        @endauthtype
        @component('miamilaw::components.form.multiselect', [
                    'name' => 'roles',
                    'description' => 'Select Roles',
                    'options' => function() use ($roles){
                        $options = [];
                        foreach ($roles as $role){
                            $options[] = [
                                'value' => $role->id,
                                'name' => $role->description,
                            ];
                        }
                        return $options;
                    },
                    'errors' => $errors,
                    ])
        @endcomponent
    @endcomponent
@endsection

src/resources/views/admin/user/edit.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    {{ $user->name }}
@endsection

@section('content')
    @component('miamilaw::components.form.form', [
                'action' => [
                    'route' => 'user.update',
                    'parameters' => [
                        'user_id' => $user->id,
                    ]
                ],
                'cancel' => [
                    'route' => 'user.index',
                    'parameters' => []
                ],
                'method' => 'PUT'
                ])
        @isadmin
            @component('miamilaw::components.form.input', [
                        'name' => 'name',
                        'icon' => 'user',
                        'placeholder' => 'Full Name',
                        'required' => true,
                        'autofocus' => true,
                        'value' => $user->name,
                        'errors' => $errors,
                        ])
            @endcomponent
            @component('miamilaw::components.form.input', [
                        'name' => 'email',
                        'icon' => 'mail',
                        'placeholder' => 'Email',
                        'required' => true,
                        'value' => $user->email,
                        'errors' => $errors,
                        ])
            @endcomponent
            @authtype('local')
                @component('miamilaw::components.form.input', [
                            'name' => 'password',
                            'type' => 'password',
                            'icon' => 'key',
                            'placeholder' => 'Update Password',
                            'errors' => $errors,
                            ])
                @endcomponent
            @elseauthtype('azure')
                @component('miamilaw::components.form.input', [
                            'name' => 'azure_id',
                            'icon' => 'cloud',
                            'placeholder' => 'Azure ID',
                            'value' => $user->azure_id,
                            'errors' => $errors,
                            ])
                @endcomponent
            @endauthtype
            @component('miamilaw::components.form.multiselect', [
                        'name' => 'roles',
                        'description' => 'Select Roles',
                        'options' => function() use ($roles, $user){
                            $options = [];
                            foreach ($roles as $role){
                                $options[] = [
                                    'value' => $role->id,
                                    'name' => $role->description,
                                    'selected' => $user->hasRole($role->name)
                                ];
                            }
                            return $options;
                        },
                        'errors' => $errors,
                        ])
            @endcomponent
        @elseisadmin
            @component('miamilaw::components.form.hidden', [
                        'name' => 'name',
                        'value' => $user->name
                        ])
            @endcomponent
            @component('miamilaw::components.form.hidden', [
                        'name' => 'email',
                        'value' => $user->email
                        ])
            @endcomponent
            @authtype('local')
                @component('miamilaw::components.form.input', [
                            'name' => 'password',
                            'type' => 'password',
                            'icon' => 'key',
                            'placeholder' => 'Update Password',
                            'errors' => $errors,
                            ])
                @endcomponent
            @endauthtype
        @endisadmin
    @endcomponent
@endsection

src/resources/views/admin/user/index.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    User Configuration
@endsection

@section('content')
    @if (session()->get('success'))
        <div class="ui positive message">
            <div class="header">{{ session()->get('success') }}</div>
        </div>
    @elseif (session()->get('warn'))
        <div class="ui warning message">
            <div class="header">
                {{ session()->get('warn') }}
            </div>
        </div>
    @endif
    <a href="{{ route('user.create') }}" class="positive ui fluid large button">
        <i class="icon plus square outline"></i>
        Create new
    </a>
    <table class="ui celled striped table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Functions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td data-label="Id">{{ $user->id }}</td>
                    <td data-label="Name"><a href="{{route('user.show', $user->id)}}">{{ $user->name }}</a></td>
                    <td data-label="Email">{{ $user->email }}</td>
                    <td data-label="Roles">
                        @forelse ($user->roles as $role)
                            {{ $role->name }}@if(!$loop->last), @endif
                        @empty
                            No roles assigned
                        @endforelse
                    </td>
                    <td data-label="Functions">
                        <form action="{{ route('user.destroy', $user)}}" method="post" onsubmit="return confirm('Are you sure you want to Delete the User?');">
                            @csrf
                            @method('DELETE')
                            <div class="ui left floated buttons">
                                <a href="{{ route('user.edit',$user->id) }}" class="ui green button">Edit</a>
                            </div>
                            <button class="ui right floated red button" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

src/resources/views/admin/user/show.blade.php
@extends('miamilaw::layouts.miamilaw')

@section('subject')
    User Profile
@endsection

@section('content')
    @if (session()->get('success'))
        <div class="ui positive message">
            <div class="header">{{ session()->get('success') }}</div>
        </div>
    @endif
    <div class="ui centered fluid card">
        <div class="content">
            <img class="right floated ui avatar image" src="{{asset('vendor/miamilaw/img/profile.jpg')}}">
            <div class="header">{{ $user->name }}</div>
            <div class="meta">
                @foreach($user->roles as $role)
                    <span>{{ $role->name }}</span>@if(!$loop->last), @endif
                @endforeach
            </div>
        </div>
        <div class="content">
            <div class="ui feed">
                <div class="event">
                    <div class="label">
                        <i class="mail icon"></i>
                    </div>
                    <div class="content">
                        <div class="summary">
                            Email
                        </div>
                        <div class="extra text">
                            {{ $user->email }}
                        </div>
                    </div>
                </div>
                @authtype('local')
                    <div class="event">
                        <div class="label">
                            <i class="key icon"></i>
                        </div>
                        <div class="content">
                            <div class="summary">
                                Password
                            </div>
                            <div class="extra text">
                                @if($user->password)
                                    Is set
                                @else
                                    Not set
                                @endif
                            </div>
                        </div>
                    </div>
                @elseauthtype('azure')
                    <div class="event">
                        <div class="label">
                            <i class="cloud icon"></i>
                        </div>
                        <div class="content">
                            <div class="summary">
                                Azure ID
                            </div>
                            <div class="extra text">
                                {{ $user->azure_id }}
                            </div>
                        </div>
                    </div>
                @endauthtype
                <div class="event">
                    <div class="label">
                        <i class="clock icon"></i>
                    </div>
                    <div class="content">
                        <div class="summary">
                            Created On
                        </div>
                        <div class="extra text">
                            {{ $user->created_at }}
                        </div>
                        <div class="meta">
                            <i class="edit icon"></i> Last modified on <div class="date">{{ $user->updated_at }}</div>
                        </div>
                    </div>
                </div>
                <div class="event">
                    <div class="label">
                        <i class="clock icon"></i>
                    </div>
                    <div class="content">
                        <div class="summary">
                            Last login
                        </div>
                        <div class="extra text">
                            {{ $user->last_login_at }} from {{ $user->last_login_ip }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="extra content">
            <span>
                <i class="user icon"></i>
                @foreach($user->roles as $role)
                    <span>{{ $role->description }}</span>@if(!$loop->last), @endif
                @endforeach
            </span>
        </div>
        <a href="{{ route('user.edit', $user->id) }}" class="ui bottom attached button">
            <i class="edit icon"></i>
            Edit
        </a>
    </div>
@endsection